// <auto-generated />
namespace TP1IdS_G15AccesoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sessions_UserName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sessions_UserName));
        
        string IMigrationMetadata.Id
        {
            get { return "202203011555101_Sessions_UserName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
